name: Develop-CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        
      - name: Run Stylelint
        run: npm run lint:styles

      - name: Build Next.js
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Verify Storybook Deployment
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "You can deploy Storybook for further testing using npm run deploy-storybook if needed."
